### ISSUE TITLE
Uncaught TypeError: markoCompiler.parseRaw is not a function

### ISSUE THREAD

**Issue by jmatc** [marko-js/atom-language-marko#15]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.10.5
**Thrown From**: [language-marko](https://github.com/marko-js/atom-language-marko) package 2.9.3

### Stack Trace

Uncaught TypeError: markoCompiler.parseRaw is not a function

```
At /Users/jocalvin/.atom/packages/language-marko/node_modules/marko-prettyprint/src/prettyPrintSource.js:23

TypeError: markoCompiler.parseRaw is not a function
  at Function.prettyPrintSource (/packages/language-marko/node_modules/marko-prettyprint/src/prettyPrintSource.js:23:29)
  at /packages/language-marko/src/index.js:73:53)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
  at CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:3:59)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/app.asar/src/command-registry.js:160:19)
  at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/app.asar/src/atom-environment.js:1162:28)
  at EventEmitter.outerCallback (/app.asar/src/application-delegate.js:312:25)
  at emitThree (events.js:116:13)
  at EventEmitter.emit (events.js:194:7)

```

### Commands

```
     -8:15.4.0 core:undo (input.hidden-input)
     -8:13.1.0 core:save (input.hidden-input)
     -8:12.7.0 core:close (input.hidden-input)
 17x -7:53.1.0 core:backspace (input.hidden-input)
     -6:01.6.0 nuclide-remote-projects:connect (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -5:29.5.0 nuclide-outline-view:toggle (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -5:02.7.0 nuclide-context-view:toggle (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -4:32.3.0 nuclide-settings:toggle (input.hidden-input)
     -3:20.3.0 nuclide-react-inspector:toggle (input.hidden-input)
  3x -2:49.7.0 nuclide-task-runner:toggle-toolbar-visibility (input.hidden-input)
     -2:22.5.0 nuclide-type-coverage:toggle-inline-display (input.hidden-input)
     -2:15 working-sets:select-active (input.hidden-input)
     -1:26.9.0 nuclide-clipboard-path:copy-repository-relative-path (ul.list-inline.tab-bar.inset-panel.nuclide-workspace-views-panel-location-tabs)
     -1:25.3.0 application:new-file (ul.list-inline.tab-bar.inset-panel)
     -1:23.7.0 core:paste (input.hidden-input)
  3x -0:56.1.0 language-marko:prettyprint (input.hidden-input)
```

### Non-Core Packages

```
file-icons 2.1.1 
formatter-json 1.0.1 
hyperclick 0.0.40 
language-ejs 0.4.0 
language-javascript-jsx 0.3.7 
language-jsx 0.1.1 
language-marko 2.9.3 
nuclide 0.211.0 
sort-lines 0.14.0 
```

**Comment by DylanPiercey** [comment]
The plugin was reworked to use our Language Server implementation. This should be fixed now.
