### ISSUE TITLE
Uncaught Error: invalid backref number/name

### ISSUE THREAD

**Issue by kuznetsov-online** [marko-js/atom-language-marko#20]
[Enter steps to reproduce:]

1. edit any .marko file
2. write 'h1 --'

**Atom**: 1.20.1 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.6
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: invalid backref number/name

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/first-mate/lib/scanner.js:33

Error: invalid backref number/name
    at Scanner.module.exports.Scanner.createScanner (/Applications/Atom.app/Contents/Resources/app/node_modules/first-mate/lib/scanner.js:33:30)
    at Scanner.module.exports.Scanner.getScanner (/Applications/Atom.app/Contents/Resources/app/node_modules/first-mate/lib/scanner.js:39:37)
    at Scanner.module.exports.Scanner.findNextMatch (/Applications/Atom.app/Contents/Resources/app/node_modules/first-mate/lib/scanner.js:58:28)
    at Rule.module.exports.Rule.findNextMatch (/Applications/Atom.app/Contents/Resources/app/node_modules/first-mate/lib/rule.js:98:34)
    at Rule.module.exports.Rule.getNextTags (/Applications/Atom.app/Contents/Resources/app/node_modules/first-mate/lib/rule.js:154:27)
    at Grammar.module.exports.Grammar.tokenizeLine (/Applications/Atom.app/Contents/Resources/app/node_modules/first-mate/lib/grammar.js:164:50)
    at TokenizedBuffer.module.exports.TokenizedBuffer.buildTokenizedLineForRowWithText (/Applications/Atom.app/Contents/Resources/app/src/tokenized-buffer.js:380:33)
    at TokenizedBuffer.module.exports.TokenizedBuffer.buildTokenizedLineForRow (/Applications/Atom.app/Contents/Resources/app/src/tokenized-buffer.js:368:25)
    at TokenizedBuffer.module.exports.TokenizedBuffer.tokenizeNextChunk (/Applications/Atom.app/Contents/Resources/app/src/tokenized-buffer.js:224:49)
    at /Applications/Atom.app/Contents/Resources/app/src/tokenized-buffer.js:206:32
    at /Applications/Atom.app/Contents/Resources/app/node_modules/underscore/underscore.js:666:53
```

### Commands

```
     -2:52.2.0 core:paste (input.hidden-input)
     -2:50.8.0 editor:newline (input.hidden-input)
     -2:50.2.0 core:move-left (input.hidden-input)
     -2:49.9.0 core:backspace (input.hidden-input)
     -2:49.6.0 core:move-up (input.hidden-input)
     -2:49.4.0 core:backspace (input.hidden-input)
     -2:48.1.0 core:save (input.hidden-input)
     -2:36.5.0 pane:show-next-recently-used-item (input.hidden-input)
     -2:36.4.0 pane:move-active-item-to-top-of-stack (input.hidden-input)
  2x -2:35.2.0 core:move-up (input.hidden-input)
     -2:34.7.0 core:move-left (input.hidden-input)
     -2:34.2.0 core:backspace (input.hidden-input)
     -2:33.7.0 core:save (input.hidden-input)
     -2:33.4.0 snippets:next-tab-stop (input.hidden-input)
     -2:33.4.0 snippets:expand (input.hidden-input)
     -2:33.4.0 editor:indent (input.hidden-input)
```

### Non-Core Packages

```
atom-yarn 0.6.0 
hyperclick 0.1.5 
language-marko 2.9.4 
nuclide 0.256.0 
platformio-ide-terminal 2.6.0 
```

**Comment by Hesulan** [comment]
This appears to happen any time `--` is typed at the end of a line where the parser is expecting a concise tag or attribute. Strangely, adding it to the beginning or middle of an existing line doesn't throw an error. This only started happening recently, right after updating Atom, so perhaps there was some sort of API change?

**Atom**: 1.19.3
**Electron**: 1.6.9
**Chrome**: 56.0.2924.87
**Node**: 7.4.0
**OS**: Ubuntu 16.04.3 LTS x64

**Comment by DylanPiercey** [comment]
The plugin was reworked to use our Language Server implementation. This should be fixed now.
