### ISSUE TITLE
Uncaught TypeError: Cannot read property 'deprecated' of undefined

### ISSUE THREAD

**Issue by BillGR17** [marko-js/atom-language-marko#21]
[Enter steps to reproduce:]

1. typing " $ name="body" value="'/absolute/path/to/index.marko'";" inside the templates body caused this error on atom

**Atom**: 1.21.1 x64
**Electron**: 1.6.15
**OS**: Linux Mint
**Thrown From**: [language-marko](https://github.com/marko-js/atom-language-marko) package 2.9.4

### Stack Trace

Uncaught TypeError: Cannot read property 'deprecated' of undefined

```
At /home/ideart/.atom/packages/language-marko/src/autocomplete/SuggestionsBuilder.js:236

TypeError: Cannot read property 'deprecated' of undefined
    at taglibLookup.forEachAttribute (/packages/language-marko/src/autocomplete/SuggestionsBuilder.js:236:25)
    at handleAttr (/packages/language-marko/node_modules/marko/dist/compiler/taglib-lookup/TaglibLookup.js:190:17)
    at findAttributesForTagName (/packages/language-marko/node_modules/marko/dist/compiler/taglib-lookup/TaglibLookup.js:200:21)
    at TaglibLookup.forEachAttribute (/packages/language-marko/node_modules/marko/dist/compiler/taglib-lookup/TaglibLookup.js:221:9)
    at SuggestionsBuilder.addAttributeSuggestions (/packages/language-marko/src/autocomplete/SuggestionsBuilder.js:235:31)
    at SuggestionsBuilder.getSuggestions (/packages/language-marko/src/autocomplete/SuggestionsBuilder.js:115:22)
    at Object.getSuggestions (/packages/language-marko/src/autocomplete/provider.js:18:46)
    at providers.forEach.provider (/opt/atom/resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:286:58)
    at Array.forEach (native)
    at AutocompleteManager.getSuggestionsFromProviders (/opt/atom/resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:262:21)
    at AutocompleteManager.findSuggestions (/opt/atom/resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:254:23)
```

### Commands

```
  2x -0:52.5.0 core:undo (input.hidden-input)
  2x -0:48.7.0 core:backspace (input.hidden-input)
     -0:40.1.0 intentions:highlight (input.hidden-input)
     -0:38.8.0 editor:newline (input.hidden-input)
  3x -0:29.4.0 core:backspace (input.hidden-input)
  4x -0:22.4.0 core:select-left (input.hidden-input)
  2x -0:19.5.0 core:move-right (input.hidden-input)
     -0:18.1.0 intentions:highlight (input.hidden-input)
     -0:17.9.0 core:paste (input.hidden-input)
     -0:17.1.0 intentions:highlight (input.hidden-input)
     -0:17 core:undo (input.hidden-input)
     -0:09.0 intentions:highlight (input.hidden-input)
     -0:08.8.0 core:paste (input.hidden-input)
  8x -0:04.8.0 core:move-right (input.hidden-input)
     -0:02.5.0 intentions:highlight (input.hidden-input)
     -0:02.3.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.30.5 
atom-handlebars 1.3.0 
busy-signal 1.4.3 
color-picker 2.2.5 
dash-syntax 0.4.1 
dash-ui 0.4.3 
emmet 2.4.3 
file-icons 2.1.13 
highlight-selected 0.13.1 
intentions 1.1.5 
javascript-snippets 1.2.1 
jquery-snippets 11.0.0 
language-marko 2.9.4 
linter 2.2.0 
linter-eslint 8.4.0 
linter-ui-default 1.6.10 
pigments 0.40.2 
platformio-ide-terminal 2.7.0 
Stylus 3.1.1 
sync-settings 0.8.3 
```

**Comment by DylanPiercey** [comment]
The plugin was reworked to use our Language Server implementation. This should be fixed now.
