### ISSUE TITLE
Uncaught Error: Cannot find module 'marko/compiler'

### ISSUE THREAD

**Issue by chengjundong** [marko-js/atom-language-marko#22]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.23.3 ia32
**Electron**: 1.6.15
**OS**: Unknown Windows version
**Thrown From**: [language-marko](https://github.com/marko-js/atom-language-marko) package 2.9.4

### Stack Trace

Uncaught Error: Cannot find module 'marko/compiler'

```
At module.js:472

Error: Cannot find module 'marko/compiler'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.23.3/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.23.3/resources/app/src/module-cache.js:354:58)
    at resolveFileName (/packages/language-marko/node_modules/marko-prettyprint/node_modules/resolve-from/index.js:17:39)
    at resolveFrom (/packages/language-marko/node_modules/marko-prettyprint/node_modules/resolve-from/index.js:31:9)
    at module.exports (/packages/language-marko/node_modules/marko-prettyprint/node_modules/resolve-from/index.js:34:41)
    at getMarkoCompiler (/packages/language-marko/node_modules/marko-prettyprint/src/util/getMarkoCompiler.js:4:27)
    at Function.prettyPrintSource (/packages/language-marko/node_modules/marko-prettyprint/src/prettyPrintSource.js:25:48)
    at HTMLElement.prettyprintCommand (/packages/language-marko/src/index.js:73:53)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.23.3/resources/app/src/command-registry.js:388:36)
    at CommandRegistry.dispatch (~/AppData/Local/atom/app-1.23.3/resources/app/src/command-registry.js:273:23)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (~/AppData/Local/atom/app-1.23.3/resources/app/src/atom-environment.js:1393:34)
    at EventEmitter.outerCallback (~/AppData/Local/atom/app-1.23.3/resources/app/src/application-delegate.js:335:31)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
  4x -0:56.8.0 core:backspace (input.hidden-input)
     -0:54.8.0 editor:newline (input.hidden-input)
     -0:51.8.0 autocomplete-plus:confirm (input.hidden-input)
     -0:51.3.0 core:move-right (input.hidden-input)
     -0:35.1.0 core:paste (input.hidden-input)
     -0:33.8.0 editor:newline (input.hidden-input)
     -0:33.6.0 snippets:next-tab-stop (input.hidden-input)
     -0:33.6.0 snippets:expand (input.hidden-input)
     -0:33.6.0 editor:indent (input.hidden-input)
     -0:33 core:backspace (input.hidden-input)
     -0:31.5.0 autocomplete-plus:confirm (input.hidden-input)
     -0:30.9.0 core:move-right (input.hidden-input)
     -0:30.6.0 core:paste (input.hidden-input)
     -0:29.8.0 core:save (input.hidden-input)
     -0:11 dev-live-reload:reload-all (input.hidden-input)
     -0:06.0 language-marko:prettyprint (input.hidden-input)
```

### Non-Core Packages

```
atom-material-syntax 1.0.2 
atom-material-ui 1.3.9 
atom-nodejs-snippets 2.0.0 
compare-files 0.8.0 
hyperclick 0.1.5 
language-marko 2.9.4 
platformio-ide-terminal 2.5.5 
```

**Comment by DylanPiercey** [comment]
The plugin was reworked to use our Language Server implementation. This should be fixed now.
