### ISSUE TITLE
Uncaught Error: An error occurred while trying to compile template at path "~/Projects/GitHub/lds...

### ISSUE THREAD

**Issue by aprasadh** [marko-js/atom-language-marko#23]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.24.0 x64
**Electron**: 1.6.16
**OS**: Mac OS X 10.13.3
**Thrown From**: [language-marko](https://github.com/marko-js/atom-language-marko) package 2.9.4

### Stack Trace

Uncaught Error: An error occurred while trying to compile template at path "/Users/guru/Projects/GitHub/lds-marko/components/lds-icon/index.marko". Error(s) in template:
1) [/Users/guru/Projects/GitHub/lds-marko/components/lds-icon/index.marko:63:0] Invalid JavaScript expression for attribute "class": Error: 
Unexpected token {: (${state.classNames})
                      ^
2) [/Users/guru/Projects/GitHub/lds-marko/components/lds-icon/index.marko:64:2] Invalid JavaScript expression for attribute "classNames": Error: 
Unexpected token {: (${state.spriteClassNames})
                      ^
3) [/Users/guru/Projects/GitHub/lds-marko/components/lds-icon/index.marko:64:2] Invalid JavaScript expression for attribute "sprite": Error: 
Unexpected token {: (${state.sprite})
                      ^

```
At /Users/guru/.atom/packages/language-marko/node_modules/marko/dist/compiler/index.js:217

Error: An error occurred while trying to compile template at path "/Users/guru/Projects/GitHub/lds-marko/components/lds-icon/index.marko". Error(s) in template:
1) [/Users/guru/Projects/GitHub/lds-marko/components/lds-icon/index.marko:63:0] Invalid JavaScript expression for attribute "class": Error: 
Unexpected token {: (${state.classNames})
                      ^
2) [/Users/guru/Projects/GitHub/lds-marko/components/lds-icon/index.marko:64:2] Invalid JavaScript expression for attribute "classNames": Error: 
Unexpected token {: (${state.spriteClassNames})
                      ^
3) [/Users/guru/Projects/GitHub/lds-marko/components/lds-icon/index.marko:64:2] Invalid JavaScript expression for attribute "sprite": Error: 
Unexpected token {: (${state.sprite})
                      ^

    at Object.parseRaw (/packages/language-marko/node_modules/marko/dist/compiler/index.js:215:21)
    at Function.prettyPrintSource (/packages/language-marko/node_modules/marko-prettyprint/src/prettyPrintSource.js:24:29)
    at HTMLElement.prettyprintCommand (/packages/language-marko/src/index.js:73:53)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:388:36)
    at CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:273:23)
    at AtomEnvironment.dispatchApplicationMenuCommand (/Applications/Atom.app/Contents/Resources/app/src/atom-environment.js:1286:25)
    at EventEmitter.outerCallback (/Applications/Atom.app/Contents/Resources/app/src/application-delegate.js:333:31)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -1:37 application:open (input.hidden-input)
     -0:55.5.0 language-marko:prettyprint (input.hidden-input)
```

### Non-Core Packages

```
atom-ide-ui 0.8.1 
atom-typescript 12.1.2 
busy-signal 1.4.3 
city-lights-syntax 1.1.6 
city-lights-ui 1.3.1 
file-type-icons 1.3.4 
hyperclick 0.0.0 
ide-java 0.7.0 
ide-json 0.2.0 
ide-python 0.7.0 
ide-rust 0.12.1 
incremental-search 5.2.2 
intentions 1.1.5 
language-lua 0.9.11 
language-marko 2.9.4 
language-rust 0.4.12 
language-scala 1.1.9 
linter 2.2.0 
linter-ui-default 1.6.10 
ocaml-merlin 0.14.4 
react 0.17.0 
symbols-tree-view 0.14.0 
teletype 0.8.0 
```

**Comment by DylanPiercey** [comment]
The plugin was reworked to use our Language Server implementation. This should be fixed now.
