### ISSUE TITLE
Uncaught Error: Cannot find module 'marko/package.json'

### ISSUE THREAD

**Issue by vandantan** [marko-js/atom-language-marko#25]
[Enter steps to reproduce:]

1. Install language-marko package.
2. Open .marko file for editing.
3. Every keystroke that changes the content of the file produces this error.

**Atom**: 1.28.1 x64
**Electron**: 2.0.4
**OS**: Ubuntu 16.04.4
**Thrown From**: [language-marko](https://github.com/marko-js/atom-language-marko) package 2.10.0

### Stack Trace

Uncaught Error: Cannot find module 'marko/package.json'

```
At module.js:545

Error: Cannot find module 'marko/package.json'
    at Module._resolveFilename (module.js:543:15)
    at Module._resolveFilename (/home/user/Downloads/atomtest/atom-1.28.1-amd64/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/home/user/Downloads/atomtest/atom-1.28.1-amd64/resources/app/src/module-cache.js:354:58)
    at resolveFileName (/packages/language-marko/node_modules/resolve-from/index.js:17:39)
    at resolveFrom (/packages/language-marko/node_modules/resolve-from/index.js:31:9)
    at module.exports (/packages/language-marko/node_modules/resolve-from/index.js:34:41)
    at Object.getMarkoMajorVersion (/packages/language-marko/src/util/marko.js:52:31)
    at /packages/language-marko/src/autocomplete/SuggestionsBuilder.js:100:44)
    at Object.getSuggestions (/packages/language-marko/src/autocomplete/provider.js:17:34)
    at providers.forEach.provider (/home/user/Downloads/atomtest/atom-1.28.1-amd64/resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:300:58)
    at Array.forEach (<anonymous>)
    at AutocompleteManager.getSuggestionsFromProviders (/home/user/Downloads/atomtest/atom-1.28.1-amd64/resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:271:21)
    at AutocompleteManager.findSuggestions (/home/user/Downloads/atomtest/atom-1.28.1-amd64/resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:263:23)
    at AutocompleteManager.requestNewSuggestions (/home/user/Downloads/atomtest/atom-1.28.1-amd64/resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:704:18)
    at AutocompleteManager.showOrHideSuggestionListForBufferChanges (/home/user/Downloads/atomtest/atom-1.28.1-amd64/resources/app/node_modules/autocomplete-plus/lib/autocomplete-manager.js:770:18)
    at Function.module.exports.Emitter.simpleDispatch (/home/user/Downloads/atomtest/atom-1.28.1-amd64/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/home/user/Downloads/atomtest/atom-1.28.1-amd64/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at TextBuffer.module.exports.TextBuffer.emitDidChangeTextEvent (/home/user/Downloads/atomtest/atom-1.28.1-amd64/resources/app/node_modules/text-buffer/lib/text-buffer.js:1792:32)
    at TextBuffer.module.exports.TextBuffer.transact (/home/user/Downloads/atomtest/atom-1.28.1-amd64/resources/app/node_modules/text-buffer/lib/text-buffer.js:996:18)
    at TextEditor.transact (/home/user/Downloads/atomtest/atom-1.28.1-amd64/resources/app/src/text-editor.js:2002:30)
    at mergeIntersectingSelections (/home/user/Downloads/atomtest/atom-1.28.1-amd64/resources/app/src/text-editor.js:1429:25)
    at TextEditor.mergeSelections (/home/user/Downloads/atomtest/atom-1.28.1-amd64/resources/app/src/text-editor.js:3419:26)
    at TextEditor.mergeIntersectingSelections (/home/user/Downloads/atomtest/atom-1.28.1-amd64/resources/app/src/text-editor.js:3390:42)
    at TextEditor.mutateSelectedText (/home/user/Downloads/atomtest/atom-1.28.1-amd64/resources/app/src/text-editor.js:1428:23)
    at TextEditor.insertText (/home/user/Downloads/atomtest/atom-1.28.1-amd64/resources/app/src/text-editor.js:1381:31)
    at TextEditor.object.(anonymous function) [as insertText] (/home/user/Downloads/atomtest/atom-1.28.1-amd64/resources/app/node_modules/underscore-plus/lib/underscore-plus.js:77:33)
    at TextEditorComponent.didTextInput (/home/user/Downloads/atomtest/atom-1.28.1-amd64/resources/app/src/text-editor-component.js:1661:30)
```

### Commands

```
     -0:06.3.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
hyperclick 0.1.5 
language-marko 2.10.0 
platformio-ide-terminal 2.8.3 
```

**Comment by shuye02** [comment]
Same thing happened to me.

**Atom**: 1.28.0 x64
**Electron**: 2.0.3
**OS**: Arch Linux

**Comment by slang800** [comment]
I got the same error. Downgrading with `apm install language-marko@2.9.4` fixed it.

**Comment by DylanPiercey** [comment]
The plugin was reworked to use our Language Server implementation. This should be fixed now.
