### ISSUE TITLE
Failed to load the language-marko package

### ISSUE THREAD

**Issue by dcDulsea** [marko-js/atom-language-marko#27]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.30.0 x64
**Electron**: 2.0.5
**OS**: Mac OS X 10.12.6
**Thrown From**: [language-marko](https://github.com/marko-js/atom-language-marko) package 2.10.0

### Stack Trace

Failed to load the language-marko package

```
At Cannot find module 'resolve-from'

Error: Cannot find module 'resolve-from'
    at Module._resolveFilename (module.js:543:15)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (<embedded>:12380:58)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (<embedded>:11724:33)
    at /packages/atom-language-marko/src/util/marko.js:2:21)
    at /packages/atom-language-marko/src/util/marko.js:81:3)
    at Module.get_Module._compile (<embedded>:11764:36)
    at Object.value [as .js] (<embedded>:12016:29)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (<embedded>:11724:33)
    at /packages/atom-language-marko/src/autocomplete/SuggestionsBuilder.js:3:19)
    at /packages/atom-language-marko/src/autocomplete/SuggestionsBuilder.js:415:3)
    at Module.get_Module._compile (<embedded>:11764:36)
    at Object.value [as .js] (<embedded>:12016:29)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (<embedded>:11724:33)
    at /packages/atom-language-marko/src/autocomplete/provider.js:7:26)
    at /packages/atom-language-marko/src/autocomplete/provider.js:40:3)
    at Module.get_Module._compile (<embedded>:11764:36)
    at Object.value [as .js] (<embedded>:12016:29)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (<embedded>:11724:33)
    at /packages/atom-language-marko/src/index.js:5:30)
    at /packages/atom-language-marko/src/index.js:109:3)
    at Module.get_Module._compile (<embedded>:11764:36)
    at Object.value [as .js] (<embedded>:12016:29)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:11:18)
    at customRequire (<embedded>:96:26)
    at Package.requireMainModule (<embedded>:75880:33)
    at measure (<embedded>:75241:22)
    at Package.measure (<embedded>:75186:25)
    at Package.load (<embedded>:75227:16)
    at PackageManager.loadAvailablePackage (<embedded>:26124:16)
    at config.transact (<embedded>:26037:20)
    at Config.transact (<embedded>:22707:20)
    at PackageManager.loadPackages (<embedded>:26035:23)
    at loadStatePromise.loadState.then (<embedded>:1080:27)
    at <anonymous>:null:null

```

### Commands

```
```

### Non-Core Packages

```
language-marko 2.10.0 
```

**Comment by DylanPiercey** [comment]
The plugin was reworked to use our Language Server implementation. This should be fixed now.
