### ISSUE TITLE
Uncaught Error: Cannot find module 'marko/compiler'Require stack:- ~/Downloads/noop.js

### ISSUE THREAD

**Issue by ritzjp** [marko-js/atom-language-marko#30]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.51.0 x64
**Electron**: 5.0.13
**OS**: macOS 11.2
**Thrown From**: [language-marko](https://github.com/marko-js/atom-language-marko) package 2.10.0

### Stack Trace

Uncaught Error: Cannot find module 'marko/compiler'
Require stack:
- /Users/ritzjp/Downloads/noop.js

```
At internal/modules/cjs/loader.js:686

Error: Cannot find module 'marko/compiler'
Require stack:
- /Users/ritzjp/Downloads/noop.js
    at Module._resolveFilename (internal/modules/cjs/loader.js:683:15)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:43:12)
    at Function.get_Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:155481)
    at resolveFileName (/packages/language-marko/node_modules/marko-prettyprint/node_modules/resolve-from/index.js:29:39)
    at resolveFrom (/packages/language-marko/node_modules/marko-prettyprint/node_modules/resolve-from/index.js:43:9)
    at module.exports (/packages/language-marko/node_modules/marko-prettyprint/node_modules/resolve-from/index.js:46:41)
    at getMarkoCompiler (/packages/language-marko/node_modules/marko-prettyprint/src/util/getMarkoCompiler.js:4:27)
    at Function.prettyPrintSource (/packages/language-marko/node_modules/marko-prettyprint/src/prettyPrintSource.js:25:48)
    at HTMLElement.prettyprintCommand (/packages/language-marko/src/index.js:73:53)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:349780)
    at CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:348255)
    at AtomEnvironment.dispatchApplicationMenuCommand (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:1:725974)
    at EventEmitter.t (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:1:733897)
    at EventEmitter.emit (events.js:194:13)
```

### Commands

```
     -1:07.2.0 language-marko:prettyprint (input.hidden-input)
     -0:47.4.0 core:paste (input.hidden-input)
     -0:40.3.0 core:save-as (input.hidden-input)
  4x -0:20.9.0 core:backspace (input.hidden-input)
     -0:16.8.0 language-marko:prettyprint (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-formatter-jsbeautify 1.1.2 
atom-prettify 0.1.3 
autocomplete-json 5.5.2 
cssbeautify 1.3.0 
formatter-jsbeautify 1.0.2 
french-menu 0.2.2 
hyperclick 0.1.5 
ide-json 0.2.1 
jade-beautify 0.1.5 
language-marko 2.10.0 
language-openscad 0.4.3 
pretty-json 2.0.3 
remote-atom 1.3.12 
```

**Comment by DylanPiercey** [comment]
The plugin was reworked to use our Language Server implementation. This should be fixed now.
