### ISSUE TITLE
Uncaught Error: Cannot find module 'marko/package.json'Require stack:- ~/dev/projets/nodejs/tes...

### ISSUE THREAD

**Issue by ritzjp** [marko-js/atom-language-marko#31]
[Enter steps to reproduce:]

1. Open a file with language marko
2. type any caracter got this message
2. ...

**Atom**: 1.51.0 x64
**Electron**: 5.0.13
**OS**: macOS 11.2
**Thrown From**: [language-marko](https://github.com/marko-js/atom-language-marko) package 2.10.0

### Stack Trace

Uncaught Error: Cannot find module 'marko/package.json'
Require stack:
- /Users/ritzjp/dev/projets/nodejs/test1/noop.js

```
At internal/modules/cjs/loader.js:686

Error: Cannot find module 'marko/package.json'
Require stack:
- /Users/ritzjp/dev/projets/nodejs/test1/noop.js
    at Module._resolveFilename (internal/modules/cjs/loader.js:683:15)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:43:12)
    at Function.get_Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:155481)
    at resolveFileName (/packages/language-marko/node_modules/resolve-from/index.js:17:39)
    at resolveFrom (/packages/language-marko/node_modules/resolve-from/index.js:31:9)
    at module.exports (/packages/language-marko/node_modules/resolve-from/index.js:34:41)
    at Object.getMarkoMajorVersion (/packages/language-marko/src/util/marko.js:52:31)
    at /packages/language-marko/src/autocomplete/SuggestionsBuilder.js:100:44)
    at Object.getSuggestions (/packages/language-marko/src/autocomplete/provider.js:17:34)
    at /Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:637679
    at Array.forEach (<anonymous>)
    at AutocompleteManager.getSuggestionsFromProviders (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:637195)
    at AutocompleteManager.findSuggestions (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:636933)
    at AutocompleteManager.requestNewSuggestions (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:645466)
    at AutocompleteManager.showOrHideSuggestionListForBufferChanges (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:646557)
    at Function.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1190297)
    at Emitter.emit (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1191738)
    at TextBuffer.emitDidChangeTextEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:505155)
    at TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:493265)
    at TextEditor.transact (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:24215)
    at /Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:16150
    at TextEditor.mergeSelections (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:39484)
    at TextEditor.mergeIntersectingSelections (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:39038)
    at TextEditor.mutateSelectedText (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:16113)
    at TextEditor.insertText (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:15662)
    at TextEditor.e.(anonymous function) [as insertText] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:258555)
    at TextEditorComponent.didTextInput (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:94346)
```

### Commands

```
     -5:48 tree-view:remove-project-folder (span.name.icon.icon-repo)
     -5:44.8.0 editor:newline (input.hidden-input)
  2x -5:42 core:backspace (input.hidden-input)
  2x -5:29.4.0 core:copy (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
  2x -0:55.5.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-formatter-jsbeautify 1.1.2 
atom-prettify 0.1.3 
autocomplete-json 5.5.4 
autocomplete-marko 2.0.0 
cssbeautify 1.3.0 
formatter-jsbeautify 1.0.2 
french-menu 1.0.0 
hyperclick 0.1.5 
hyperclick-marko 2.0.0 
ide-json 0.2.1 
jade-beautify 0.1.5 
language-marko 2.10.0 
language-openscad 0.4.3 
pretty-json 2.1.2 
remote-atom 1.3.12 
```

**Comment by DylanPiercey** [comment]
The plugin was reworked to use our Language Server implementation. This should be fixed now.
